services:
  auctions:
    container_name: auctions_app
    image: auctions
    build:
      context: .
      dockerfile: Auctions/Dockerfile
    environment:
      ConnectionString__DefaultConnection: ""

    depends_on:
      - postgres
  postgres:
    container_name: auctions_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auctionsDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - storage-minio:/data
    command: server --address ":9099" --console-address ":9000" /data
    restart: always

volumes:
  postgres_data:
  storage-minio:
